"""
Export Agent — Generates PDF and Excel reports from chart data + insights.
PDF: styled report with chart placeholder, insights narrative, and AI summary.
Excel: formatted multi-sheet workbook with data, insights, and strategy tables.
"""
import io
import logging
from typing import Dict, List, Optional, Any
from datetime import datetime

logger = logging.getLogger(__name__)


class ExportAgent:
    """Exports dashboard panels to PDF or Excel format."""

    async def export_pdf(
        self,
        title: str,
        insights: List[Dict],
        data: List[Dict],
        strategies: List[Dict],
        tts_text: Optional[str] = None,
    ) -> bytes:
        """
        Generate a PDF report with insights narration and data summary.
        Returns raw bytes of the PDF.
        """
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.colors import HexColor, white
            from reportlab.lib.units import cm
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer,
                Table, TableStyle, HRFlowable,
            )

            buf = io.BytesIO()
            doc = SimpleDocTemplate(
                buf,
                pagesize=A4,
                rightMargin=2 * cm,
                leftMargin=2 * cm,
                topMargin=2 * cm,
                bottomMargin=2 * cm,
            )

            styles = getSampleStyleSheet()
            BLUE = HexColor("#0078D4")
            DARK = HexColor("#201F1E")
            GRAY = HexColor("#605E5C")
            LIGHT = HexColor("#F3F2F1")
            RED   = HexColor("#D13438")
            GREEN = HexColor("#107C10")

            h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=22, textColor=BLUE, spaceAfter=6)
            h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=14, textColor=DARK, spaceAfter=4)
            body = ParagraphStyle("body", parent=styles["Normal"], fontSize=10, textColor=GRAY, leading=16)
            caption = ParagraphStyle("caption", parent=styles["Normal"], fontSize=9, textColor=GRAY, italic=True)

            story = []
            ts = datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC")

            # Header
            story.append(Paragraph(title or "Business Intelligence Report", h1))
            story.append(Paragraph(f"Generated by Talking BI · {ts}", caption))
            story.append(HRFlowable(width="100%", thickness=1, color=BLUE, spaceAfter=16))

            # Executive Summary (TTS text)
            if tts_text:
                story.append(Paragraph("Executive Summary", h2))
                story.append(Paragraph(tts_text, body))
                story.append(Spacer(1, 12))

            # Insights
            if insights:
                story.append(Paragraph("Key Insights", h2))
                for ins in insights[:5]:
                    direction = ins.get("direction", "neutral")
                    arrow = "▲" if direction == "up" else ("▼" if direction == "down" else "–")
                    color = GREEN if direction == "up" else (RED if direction == "down" else GRAY)
                    change = f" {ins['change_pct']:+.1f}%" if ins.get("change_pct") is not None else ""
                    story.append(Paragraph(f"<font color='#{color.hexval()[2:]}'>{arrow}</font> <b>{ins.get('title', '')}</b>{change}", body))
                    story.append(Paragraph(ins.get("body", ""), body))
                    if ins.get("action"):
                        story.append(Paragraph(f"→ <i>{ins['action']}</i>", caption))
                    story.append(Spacer(1, 6))
                story.append(Spacer(1, 8))

            # Strategies
            if strategies:
                story.append(Paragraph("Strategic Recommendations", h2))
                for rec in strategies[:3]:
                    story.append(Paragraph(f"<b>{rec.get('title', '')}</b>", body))
                    story.append(Paragraph(rec.get("reasoning", ""), body))
                    story.append(Spacer(1, 6))
                story.append(Spacer(1, 8))

            # Data Table (first 20 rows)
            if data:
                story.append(Paragraph("Data", h2))
                cols = list(data[0].keys())[:8]  # Max 8 columns
                table_data = [cols] + [[str(row.get(c, ""))[:30] for c in cols] for row in data[:20]]

                tbl = Table(table_data, repeatRows=1)
                tbl.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), BLUE),
                    ("TEXTCOLOR", (0, 0), (-1, 0), white),
                    ("FONTSIZE", (0, 0), (-1, 0), 9),
                    ("FONTSIZE", (0, 1), (-1, -1), 8),
                    ("BACKGROUND", (0, 1), (-1, -1), LIGHT),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, LIGHT]),
                    ("GRID", (0, 0), (-1, -1), 0.25, GRAY),
                    ("PADDING", (0, 0), (-1, -1), 4),
                ]))
                story.append(tbl)

            doc.build(story)
            return buf.getvalue()

        except ImportError:
            logger.error("reportlab not installed — cannot generate PDF")
            raise RuntimeError("PDF export requires 'reportlab'. Run: pip install reportlab")

    async def export_excel(
        self,
        title: str,
        data: List[Dict],
        insights: List[Dict],
        strategies: List[Dict],
    ) -> bytes:
        """
        Generate a styled Excel workbook.
        Sheet 1: Data, Sheet 2: Insights, Sheet 3: Strategy Table
        Returns raw bytes of the .xlsx file.
        """
        try:
            import openpyxl
            from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
            from openpyxl.utils import get_column_letter

            wb = openpyxl.Workbook()

            BLUE_FILL = PatternFill("solid", fgColor="0078D4")
            GRAY_FILL = PatternFill("solid", fgColor="F3F2F1")
            GREEN_FILL = PatternFill("solid", fgColor="DFF6DD")
            RED_FILL   = PatternFill("solid", fgColor="FDE7E9")
            HEADER_FONT = Font(bold=True, color="FFFFFF", name="Segoe UI", size=11)
            BODY_FONT   = Font(name="Segoe UI", size=10)
            TITLE_FONT  = Font(bold=True, name="Segoe UI", size=16, color="0078D4")
            thin = Side(style="thin", color="EDEBE9")
            border = Border(left=thin, right=thin, top=thin, bottom=thin)

            def header_row(ws, headers, row=1):
                for col, h in enumerate(headers, 1):
                    cell = ws.cell(row=row, column=col, value=h)
                    cell.fill = BLUE_FILL
                    cell.font = HEADER_FONT
                    cell.alignment = Alignment(horizontal="center")
                    cell.border = border

            def auto_width(ws):
                for col in ws.columns:
                    max_len = max((len(str(c.value or "")) for c in col), default=10)
                    ws.column_dimensions[get_column_letter(col[0].column)].width = min(max_len + 4, 40)

            # ── Sheet 1: Data ─────────────────────────────────────────────────
            ws = wb.active
            ws.title = "Data"
            ws["A1"] = title or "Talking BI Export"
            ws["A1"].font = TITLE_FONT
            ws["A2"] = f"Exported: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
            ws["A2"].font = Font(name="Segoe UI", size=9, color="605E5C", italic=True)

            if data:
                cols = list(data[0].keys())
                header_row(ws, cols, row=4)
                for r, row in enumerate(data, start=5):
                    fill = GRAY_FILL if r % 2 == 0 else PatternFill()
                    for c, col in enumerate(cols, 1):
                        cell = ws.cell(row=r, column=c, value=row.get(col))
                        cell.font = BODY_FONT
                        cell.border = border
                        if r % 2 == 0:
                            cell.fill = GRAY_FILL

            ws.freeze_panes = "A5"
            auto_width(ws)

            # ── Sheet 2: Insights ─────────────────────────────────────────────
            ws2 = wb.create_sheet("Insights")
            header_row(ws2, ["Title", "Summary", "Metric", "Change %", "Direction", "Action"], row=1)
            for r, ins in enumerate(insights, start=2):
                direction = ins.get("direction", "neutral")
                fill = GREEN_FILL if direction == "up" else (RED_FILL if direction == "down" else PatternFill())
                vals = [
                    ins.get("title", ""), ins.get("body", ""), ins.get("metric", ""),
                    ins.get("change_pct"), direction, ins.get("action", ""),
                ]
                for c, v in enumerate(vals, 1):
                    cell = ws2.cell(row=r, column=c, value=v)
                    cell.font = BODY_FONT
                    cell.fill = fill
                    cell.border = border
            auto_width(ws2)

            # ── Sheet 3: Strategy ─────────────────────────────────────────────
            if strategies:
                ws3 = wb.create_sheet("Strategy")
                header_row(ws3, ["Title", "Priority", "Reasoning", "Expected Impact"], row=1)
                for r, s in enumerate(strategies, start=2):
                    vals = [s.get("title"), s.get("priority"), s.get("reasoning"), s.get("expected_impact")]
                    for c, v in enumerate(vals, 1):
                        cell = ws3.cell(row=r, column=c, value=v)
                        cell.font = BODY_FONT
                        cell.border = border
                auto_width(ws3)

            buf = io.BytesIO()
            wb.save(buf)
            return buf.getvalue()

        except ImportError:
            logger.error("openpyxl not installed — cannot generate Excel")
            raise RuntimeError("Excel export requires 'openpyxl'. Run: pip install openpyxl")
